version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      - MYSQL_DATABASE=BooksWaka
      - MYSQL_ROOT_PASSWORD=psw123
      - MYSQL_CHARACTER_SET_SERVER= utf8mb4
      - MYSQL_COLLATION_SERVER= utf8mb4_unicode_ci
    ports:
      - "6603:3306"
    volumes:
      - ./mysql/init_db:/docker-entrypoint-initdb.d
    networks:
      - backend
  mysql_api:
    container_name: mysql_api_container
    build: ./mysql_api
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    volumes:
      - ./mysql_api:/app
    environment:
      FLASK_ENV: development
    networks:
      - frontend
      - backend
  waka_page:
    container_name: waka_page
    build: ./waka-page
    ports:
      - "3001:3000"
    depends_on:
      - mysql_api
    volumes:
      - ./waka-page:/user/src/app
    networks:
      - frontend
  crawl_api:
    container_name: crawl_api_container
    build: ./crawl_api
    ports:
      - "5556:5555"
    depends_on:
      - mysql_api
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
